name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/secure-drop/secure-drop
            git pull origin main
            docker compose up -d --build
            docker compose exec -u root app chmod -R 777 storage bootstrap/cache
            docker compose exec app php artisan config:cache
            docker compose exec app php artisan route:cache
